name: gameTest
on: [pull_request, push]

jobs:
  gameTest:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v5
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: setup jdk
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: runGameTestServer
        run: ./gradlew runGameTestServer
        env:
          DR_KEY: ${{ secrets.DR_KEY }}